---
title: "Work"
author: "Hayley Lenamon"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true
---

## WRGW Music Blog

**Noah Kahan at the 9:30 Club, 11/13**

Born in Hanover, New Hampshire and a proud New-Englander, Noah Kahan is a folk-pop singer and songwriter who is playing at the 9:30 Club on November 13, along with Australian-born artist Blake Rose as the opening act. 

Kahan released his first single “Young Blood” in 2017, which received over 9 million views and led to the creation of his first full-length studio album Busyhead in 2019. During the spring of 2020, amidst Kahan’s quarantine stay at his father’s home in Vermont, he recorded Cape Elizabeth, a 5-track EP with an acoustic, tranquil sound. His most recent album, I Was/I Am, dropped this past September and includes the songs “Part of Me”, “Godlight”, and “Animal”, to name a few. This album is leading Kahan’s tour this fall, however his set list is bound to incorporate songs from his previous tracks as well. 

As an avid listener to Kahan’s music, I have no doubt that his tour will be one for the books. Tickets to see Noah Kahan at the 9:30 Club on 11/13 are currently sold out, but resale tickets are likely still available. Doors open at 6:00pm, so make sure to get in line early to claim your spot near the stage. Oh, and don’t forget to wear your flannel and blundstones.

**Wild Pink at Songbyrd, 9/14**

Born out of the streets of New York City in 2015, Wild Pink is an indie-rock band that makes music from the depths of the heart and the profundities of the mind. While the band’s main face is John Ross, who takes the lead on vocals and guitar, the trio is complete by bassist T.C. Brownell and Dan Keegan on drums. Wild Pink’s first studio album titled Wild Pink debuted in 2017, though they put out a variety of EPs prior. Following the release of indie-punk album, Wild Pink, was their second album Yolk in the Fur in 2018, and in February of 2021, the band dropped A Billion Little Lights, marking their third studio album. 

A common theme can be strung throughout Wild Pink’s music, yet it is strengthened more and more in their recent releases. That theme is unearthing some of life’s truths and coping with the uncertainty of the future, or rather, grasping onto our childhood experiences and growing with them through the natural timeline of human existence. There also happens to be an obvious emphasis on nature, as many of Wild Pink’s songs encompass acoustic and folk-like melodies that will lead you to find yourself lost in a daydream filled with clarity and content. 

A Billion Little Lights has received much praise from top music critics such as Pitchfork, NPR, Billboard, and more. As of August, the band released a live version of their song “Amalfi”, taking on a simplistic and poetic-like sound that, to me, is reminiscent of an unfeigned love story; perhaps one that may not relate to human beings, but instead to an individual’s connection with the natural world. 

Wild Pink will be performing alongside Chicago-based indie-folk band, Ratboys. Transpiring from college dorm-room camaraderie and a shared knack for music, Ratboys are celebrating their 10 year anniversary as an official band with their latest album Happy Birthday, Ratboy. Catch Ratboys & Wild Pink live at Songbyrd in Adams Morgan on 9/13 or 9/14 at 7pm. Tickets are selling fast so be sure to get yours soon, and expect to hear well-admired songs from Wild Pink’s A Billion Little Lights, which may provide you with an escape that you didn’t know you needed. Fun Fact: If you are a fan of the comedy television series ‘Schitt’s Creek’, Annie Murphy (who plays Alexis Rose) stars in Wild Pink’s music video for “The Shining But Tropical” from A Billion Little Lights. 



